export enum SLIDER {
  MIN = -30,
  MID = 40,
  MAX = 130,
}

export enum FACE_STATE {
  MIN_MISERABLE = SLIDER.MIN,
  MAX_MISERABLE = -20,
  MIN_SAD = -20,
  MAX_SAD = 20,
  MIN_DEPRESSED = 20,
  MAX_DEPRESSED = SLIDER.MID,
  MIN_CALM = SLIDER.MID,
  MAX_CALM = 50,
  MIN_SMILING = 50,
  MAX_SMILING = 70,
  MIN_HAPPY = 70,
  MAX_HAPPY = 90,
  MIN_CHEERFUL = 90,
  MAX_CHEERFUL = SLIDER.MAX,
}
